eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka-server:8761/eureka}
#   instance:
#     hostname: localhost

